minimumReleaseAge: '10080' # in minutes (7 days)

patchedDependencies:
  '@vue/compiler-vapor@3.6.0-alpha.7': patches/@vue__compiler-vapor@3.6.0-alpha.7.patch
  vite-svg-loader@5.1.0: patches/vite-svg-loader@5.1.0.patch
